#!/usr/bin/env bash

################################################################################
#                     CostAlarm for Amazon Web Services                        #
#               Copyright (C) 2011 Shore Labs for costalarm.com                #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of this software and associated documentation files (the "Software"), to deal#
# in the Software without restriction, including without limitation the rights #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell    #
# copies of the Software, and to permit persons to whom the Software is        #
# furnished to do so, subject to the following conditions:                     #
#                                                                              #
# The above copyright notice and this permission notice shall be included in   #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE  #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER       #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,#
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN    #
# THE SOFTWARE.                                                                #
#                                                                              #
# Amazon Web Services and AWS are trademarks of Amazon.com, Inc. or its        #
# affiliates in the United States and/or other countries.                      #
#                                                                              #
################################################################################

#
# Source configuration files
#

# Global configuration file
if [ -f /etc/costalarm/config ]
then
    source /etc/costalarm/config
fi

# User configuration file
if [ -f ~/.costalarmrc ]
then
    source ~/.costalarmrc
fi

echo "GET http://costalarm.com/api/v1/statements/show.txt?api_token=$API_TOKEN&type=monthly"
echo ""

curl "http://costalarm.com/api/v1/statements/show.txt?api_token=$API_TOKEN&type=monthly"
echo ""
